### ISSUE TITLE
Tag search ignores inherited tags

### ISSUE THREAD

**Issue by ashiklom** [alphapapa/org-rifle#34]
Tags [inherited](https://orgmode.org/manual/Tag-inheritance.html) by subheadings currently do not show up in `helm-org-rifle`. For instance...

```
* My heading :tag1:
** My sub 1
** My sub 2
```

By default both `My sub 1` and `My sub 2` inherit `:tag1`, but a `helm-org-rifle` search for `:tag1` only produces `My heading` as a result.

**Comment by rodelrod** [comment]
Hi, thank you for your work.

I have the same problem. In my workflow I use `org-archive-to-archive-sibling`, so I need to be able to negate inherited archive tags in the search (`!:ARCHIVE:`) if I want to reliable exclude archived items from the search.

**Comment by alphapapa** [comment]
@ashiklom @rodelrod I've been busy with other things and forgot about this.

I think, probably, I either decided against tag inheritance, or decided to not bother making it work, because it tends to be slow without caching, as each heading requires looking up the outline tree to collect ancestor tags.  Org has some caching features, but I think those generally are for `org-map-entries`, which we don't use, because that would be very slow.

I guess the feature could be optionally enabled anyway, but it could be very slow, depending on circumstances.  Otherwise, I guess we'd have to implement our own caching mechanism, which might make it acceptably fast.

I don't know if I'll have time to work on this soon, so feel free to ping me here to remind me.  :)  Thanks.

**Comment by rodelrod** [comment]
I understand, sounds like a challenging issue. 

I still haven't figured out a decent archiving workflow, one which would allow me to get an uncluttered view when refiling or organizing ongoing projects, but still easily find when a particular sequence of events happened in the past.

This issue closes some doors but I'll keep trying.

Thank you

**Comment by mchenry66** [comment]
Ran into this issue.  My use case is that I want to discriminate between mere mentions in meeting or working notes from those that are within a tree of references (denoted with an inherited tag like :ref: ).    I don't immediately see an alternative method for me short of tagging each  entry,   or refiling all references  to a dedicated file or parent tree.   Neither is attractive.

So  just putting in  my  vote for the feature (and  to say thanks for the awesome code).

**Comment by alphapapa** [comment]
@mchenry66 Thanks.  I hope to solve this issue someday, but I don't have any immediate plans.  It might be best solved in a way that could be used by packages other than just this one.  Org does have some caching for inherited tags, but it seems tightly intertwined with its searching code in a way that's not easy to use from other code.  I'll have to look at it again sometime.

**Comment by alphapapa** [comment]
For the record, I don't plan to implement this in `org-rifle`, because it's already implemented in [org-ql](https://github.com/alphapapa/org-ql), which basically supersedes `org-rifle`.  I generally recommend using the `helm-org-ql` command now.  The only feature that `helm-org-rifle` has that `helm-org-ql` doesn't is showing entry content, but that will be easily added to `helm-org-ql` in the future (and at that point, I might turn `helm-org-ql` into `org-rifle` 2.0 or something like that).
