### ISSUE TITLE
Performance bug related to cache

### ISSUE THREAD

**Issue by wrycode** [alphapapa/org-rifle#47]
When I initially run `helm-org-rifle-org-directory` it takes about 5 seconds to show results. It stays this way for every search until I run `helm-org-ql-org-directory` just once from your org-ql package. After that, `helm-org-rifle-org-directory` is instantaneous (and awesome!). If I restart Emacs the rifle command is slow again until I run `helm-org-ql-org-directory`.

I will double check with `emacs -q` and try to make this reproducible soon, but since you're the author of both packages I thought you might have a hunch about this interaction already

**Comment by alphapapa** [comment]
There is no interaction between `helm-org-rifle` and `org-ql`.  Neither of them uses code from the other package.  `helm-org-rifle` has no caching.

Probably the issue is that, when you first run the command, the files in `org-directory` are not already loaded.  They have to be loaded before they can be searched.  Depending on your configuration and the size of the files, it can take some time for Org to load them.

I use `desktop-mode` to preload my Org files when Emacs is idle.

**Comment by wrycode** [comment]
>Probably the issue is that, when you first run the command, the files in `org-directory` are not already loaded.  They have to be loaded before they can be searched.  Depending on your configuration and the size of the files, it can take some time for Org to load them.
>
>I use `desktop-mode` to preload my Org files when Emacs is idle.

You're completely right. I must have been running org-rifle too soon
after opening Emacs. Thank you.
