### ISSUE TITLE
Question: Is there a way to restrict only to headings

### ISSUE THREAD

**Issue by guraltsev** [alphapapa/org-rifle#54]
Sometimes I search for a word that occurs often in my org files, maybe too often to be useful. However I know that I only have one section that has that as a heading. Is there a way to tell rifle to only look at headings?

**Comment by alphapapa** [comment]
That is not currently implemented in this package, however see https://github.com/alphapapa/org-ql

**Comment by guraltsev** [comment]
Thanks! I am configuring my emacs and I am slightly confused: what are the use-cases/advantages of `helm-org-rifle` vs `helm-org-ql`? Which should I use? Sorry for the naive question.

**Comment by alphapapa** [comment]
Please consult the extensive documentation and screenshots in the readme files.  Use whichever you like, or both.  I do.

**Comment by michaeldickens** [comment]
I also wanted this feature, so I created a pull request to implement it: https://github.com/alphapapa/org-rifle/pull/62

**Comment by alphapapa** [comment]
@michaeldickens Thanks, but I don't think it's a good idea to implement this feature in `org-rifle`, because it already exists in `org-ql`, which mostly obsoletes `org-rifle` and is much faster.  In the future, `org-rifle` will probably either directly suggest that users use `org-ql` instead, or I may rewrite it to use `org-ql` as a backend.
