### ISSUE TITLE
Support for ivy?

### ISSUE THREAD

**Issue by x-ji** [alphapapa/org-rifle#59]
There was an issue https://github.com/alphapapa/org-rifle/issues/15 three years ago which asked whether it would be possible to integrate this with ivy, and the reply was that there ivy lacks some of the features provided by helm, so such an idea would need exploring. I wonder if something has been done in the time since, or maybe it is not that practical after all.

This package is wonderful and I have no problem switching to Helm just for it. Ivy has usually been much more responsive for me though so if something similar could also be done in ivy it would be awesome.

**Comment by alphapapa** [comment]
Using Ivy would mean giving up much of the functionality provided by this package, such as using separate sources per file, acting on multiple items, using different actions, etc.  Ivy is a fine tool, but it is less capable than Helm.  Ivy is basically an enhanced completion method, while Helm is much more powerful.

Using Ivy for this wouldn't make it faster.  Helm is not slow--that is a common misconception, a myth propagated by people who seem to feel like Helm is icky and that their Emacs config would be marred by having it installed, a blemish on their otherwise pure and clean collection of packages.

Note as well that this package already contains a non-Helm UI in the `occur` commands.

See also: `org-ql`.

**Comment by x-ji** [comment]
Thanks for the link and the explanation. Yeah I think it's true that a lot of people tend to criticize Helm in the sense that they feel it's a bloated piece of software. I do feel a bit of a slowdown when using Helm but it might well be due to the way it's configured. And if there are no other CPU-intensive tasks running the responsiveness is still fine. `org-ql` seems great. I will check it out.
